# Generated by Django 5.0.6 on 2024-05-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='product_images',
            field=models.ImageField(blank=True, upload_to='photos/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_images_1',
            field=models.ImageField(blank=True, upload_to='photos/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_images_2',
            field=models.ImageField(blank=True, upload_to='photos/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_images_3',
            field=models.ImageField(blank=True, upload_to='photos/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('250gm', '250gm'), ('500gm', '500gm'), ('1kg', '1kg')], max_length=10, null=True),
        ),
    ]
