# Generated by Django 5.0.6 on 2024-06-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_images_product_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_images_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_images_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_images_3',
        ),
    ]
