# Generated by Django 5.0.6 on 2024-06-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_product_images_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_images_1',
            field=models.ImageField(blank=True, upload_to='photos/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_images_2',
            field=models.ImageField(blank=True, upload_to='photos/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_images_3',
            field=models.ImageField(blank=True, upload_to='photos/products/'),
        ),
    ]
