# Generated by Django 5.0.6 on 2024-06-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_product_images_1_product_product_images_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_avilable',
            new_name='is_available',
        ),
    ]
